from game import models
from entityCode import jsonMessages

models.Map.objects.all().delete()
models.Tile.objects.all().delete()
models.EntityType.objects.all().delete()
models.State.objects.all().delete()
models.Trigger.objects.all().delete()
models.Behaviour.objects.all().delete()
models.ActuatorType.objects.all().delete()
models.EntityInstance.objects.all().delete()
models.Actuator.objects.all().delete()

sand = models.Tile(name='sand', walkable=True)
sand.save()
water = models.Tile(name='water', walkable=False)
water.save()
fire = models.Tile(name='FIRE', walkable=False)
fire.save()

switch = models.EntityType(name='switch', sprite='switch.png', type='switch')
switch.save()
lamp = models.EntityType(name='lamp', sprite='lamp.png', type='lamp')
lamp.save()
state = models.State(name='on?', entityType=switch)
state.save()
lstate = models.State(name='on?', entityType=lamp)
lstate.save()
beh = models.Behaviour(name='toggle', entityType=switch)
beh.save()
lbeh = models.Behaviour(name='toggle', entityType=lamp)
lbeh.save()
trig = models.Trigger(name='press')
trig.save()
act = models.ActuatorType(entityType=switch, behaviour=beh, trigger=trig)
act.save()

map = models.Map(name='wallyTest', sizex=3, sizey=3, tiles=[1,2,3], tilemap=[1,1,1,2,2,2,3,3,3])
map.save()
mySwitch = models.EntityInstance(type=switch, posx=64, posy=0, map=map)
mySwitch.save()
myLamp = models.EntityInstance(type=lamp, posx=128, posy=64, map=map)
myLamp.save()
myAct = models.Actuator(type=act, owner=mySwitch, target=myLamp)
myAct.save()
wally = models.Wall(sprite='wally', crossable=False, originx=1, originy=1, finalx=2, finaly=1, map = map)
wally.save()

w = models.WorldState(state=lstate, map=map, value=False)
w.save()

print jsonMessages.convertMapToJSON(map.name)