{"map":{
	"tilemap":[[1,1,1,3,1,1],[1,1,2,1,2,1],[1,2,2,2,2,2],[1,2,2,2,2,3],[1,2,2,2,2,3]],
	"entities":{
		"3,2":{
			"name":"switchat32",
			"type":"switch",
			"sprite":"/static/pj/switch.gif",
			"triggers":["press"],
			"behaviours":["toggle","break"],
			"xy":"3,2"
		},
		"5,2":{
			"name":"switchat52",
			"type":"switch",
			"sprite":"/static/pj/switch.gif",
			"triggers":["press"],
			"behaviours":["toggle","break"],
			"xy":"5,2"
		},
		"6,1":{
			"name":"lampat61",
			"type":"lamp",
			"sprite":"/static/pj/lamp.png",
			"triggers":["press"],
			"behaviours":["toggle","break"],
			"xy":"6,1"
		},
		"6,5":{
			"name":"lampat65",
			"type":"lamp",
			"sprite":"/static/pj/lamp.png",
			"triggers":["press"],
			"behaviours":["toggle","break"],
			"xy":"6,5"
		},
		"1,5":{
			"name":"lampat15",
			"type":"lamp",
			"sprite":"/static/pj/lamp.png",
			"triggers":["press"],
			"behaviours":["toggle","break"],
			"xy":"1,5"
		},
		"1,1":{
			"name":"lampat11",
			"type":"lamp",
			"sprite":"/static/pj/lamp.png",
			"triggers":["press"],
			"behaviours":["toggle","break"],
			"xy":"1,1"
		}
	},
	"actuators":{
		"switchat32":{
			"press":[
			{"behaviour":"toggle",
			"target":"lampat11"},
			{"behaviour":"break",
			"target":"lampat15"}
		]},
		"switchat52":{
			"press":[
			{"behaviour":"toggle",
			"target":"lampat61"},
			{"behaviour":"break",
			"target":"lampat65"}
		]},
		"lampat61":{},
		"lampat65":{},
		"lampat15":{},
		"lampat11":{}
	},
	"name":"Name here"
}}